version: '3.9'

services:

  postgres_db:
    container_name: flago-backend
    image: postgres:16.2-alpine3.19
    restart: always
    # # set shared memory limit when using docker-compose
    # shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: flago_password
      POSTGRES_USER: flago_user
      POSTGRES_DB: flago
      POSTGRES_PORT: 5432
    networks:
      - flago_net

  app:
    container_name: flago-frontend
    build: .
    depends_on:
      - postgres_db
    ports:  
      - 82:8080
    environment:
      PG_Port: 5432
      PG_Host: postgres_db
      PG_User: ${DATABASE_USER}
      PG_Password: ${DATABASE_PW}
      PG_DB: ${DATABASE_DB}
    networks:
      - flago_net

networks:
  flago_net:
    name: flago_net